on:
  workflow_call:
    inputs:
      artifactName:
        required: false
        type: string

      artifactPath:
        required: false
        type: string

      app:
        description: Provides the App specifier ({app}/{stage}, ex. webapp-playdemo/dev)
        required: true
        type: string

      yqEval:
        description: Specifies yq eval string to update version file
        required: true
        type: string

      tags:
        description: Images tags
        required: true
        type: string

jobs:
  build-image:
    name: Push and update values repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - if: |
          inputs.artifactName != ''

        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ inputs.artifactPath }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            c8n.io/${{ github.repository }}
          tags: |
            ${{ inputs.tags }}

      -
        name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: c8n.io
          username: ${{ secrets.C8N_USERNAME }}
          password: ${{ secrets.C8N_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: docker/Dockerfile
          ## path form to override the git only context
          context: .

      - name: Update Helm values repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Write image version
          inputs: '{ "basePath": "${{ inputs.app }}", "yqEval": "${{ inputs.yqEval }}" }'
          repo: dennybaa/cue-values
          token: ${{ secrets.GH_TOKEN }}
          ref: refs/heads/main
