on: workflow_call

jobs:
  golangci:
    name: Golang CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
